services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: "traefik:v3.2.1"
    command:      
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=araristaf@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
    container_name: "traefik"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend:
    image: ahmedrachid04/dht-frontend:latest
    ports:
    - "3000:80"
    depends_on:
      - backend
    restart: always
  backend:
    image: ahmedrachid04/dht-backend:latest
    environment:
      - POSTGRES_USER=
      - POSTGRES_HOST=
      - POSTGRES_PASSWORD=
      - POSTGRES_DATABASE=
      - POSTGRES_ENDPOINT_ID=
      - POSTGRES_PORT=
      - TELEGRAM_BOT_AUTH_TOKEN=
      - TELEGRAM_CHAT_ID=
      - ALLOWED_ORIGINS=
      - SMTP_HOST=
      - SMTP_PORT=
      - SENDER_EMAIL=
      - SMTP_PASSWORD=
      - ALLOWED_HOSTS=
      - TWILLIO_AUTH_TOKEN=
      - TWILLIO_SID=
    env_file:
      - .env.production
    ports:
    - "5000:80"
    restart: always
    
volumes:
  letsencrypt:
        
